steps:
  - name: python
    entrypoint: pip
    args: ['install', '-r', 'requirements.txt', '--user']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us.gcr.io/sainathcloudcomputing/group9cloudproject:latest']